-- ==========================================================
-- FINPULSE & SUPABASE SCHEMA SETUP SCRIPT
-- Copy toàn bộ nội dung file này dán vào Supabase Dashboard -> SQL Editor -> Run
-- ==========================================================

-- 1. Tạo Enums
DO $$ BEGIN
    CREATE TYPE "Role" AS ENUM ('ADMIN', 'EDITOR');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "PostStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Bảng Users (Admin / Tác giả)
CREATE TABLE IF NOT EXISTS "users" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'ADMIN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Bảng Categories (Danh mục)
CREATE TABLE IF NOT EXISTS "categories" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL UNIQUE,
    "description" TEXT,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Bảng Posts (Bài viết phân tích)
CREATE TABLE IF NOT EXISTS "posts" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "title" TEXT NOT NULL,
    "slug" TEXT NOT NULL UNIQUE,
    "excerpt" TEXT,
    "content" TEXT NOT NULL,
    "coverImage" TEXT,
    "status" "PostStatus" NOT NULL DEFAULT 'DRAFT',
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "views" INTEGER NOT NULL DEFAULT 0,
    "categoryId" TEXT NOT NULL REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "authorId" TEXT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Bảng Tags
CREATE TABLE IF NOT EXISTS "tags" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL UNIQUE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. Bảng trung gian Post_Tags
CREATE TABLE IF NOT EXISTS "post_tags" (
    "postId" TEXT NOT NULL REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "tagId" TEXT NOT NULL REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY ("postId", "tagId")
);

-- 7. Bảng Todos (Mẫu test nhanh theo hướng dẫn Supabase Quickstart)
CREATE TABLE IF NOT EXISTS "todos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "is_complete" BOOLEAN DEFAULT false,
    "inserted_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Chèn dữ liệu mẫu cho Todos
INSERT INTO "todos" ("name") VALUES 
('Khởi tạo Supabase cho FinPulse'),
('Đồng bộ dữ liệu phân tích doanh nghiệp')
ON CONFLICT DO NOTHING;

-- 8. Cấu hình Row Level Security (RLS) để cho phép đọc dữ liệu công khai qua Supabase API
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "post_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "todos" ENABLE ROW LEVEL SECURITY;

-- Tạo chính sách cho phép đọc công khai (SELECT)
DROP POLICY IF EXISTS "Cho phép đọc categories công khai" ON "categories";
CREATE POLICY "Cho phép đọc categories công khai" ON "categories" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Cho phép đọc posts đã xuất bản" ON "posts";
CREATE POLICY "Cho phép đọc posts đã xuất bản" ON "posts" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Cho phép đọc tags công khai" ON "tags";
CREATE POLICY "Cho phép đọc tags công khai" ON "tags" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Cho phép đọc post_tags công khai" ON "post_tags";
CREATE POLICY "Cho phép đọc post_tags công khai" ON "post_tags" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Cho phép đọc todos" ON "todos";
CREATE POLICY "Cho phép đọc todos" ON "todos" FOR SELECT USING (true);
